repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black --check .
      language: system
      types: [python]
      pass_filenames: false

    - id: isort
      name: isort
      entry: isort --check-only .
      language: system
      types: [python]
      pass_filenames: false

    - id: py.test
      name: pytest
      entry: py.test ./src
      language: system
      types: [python]
      pass_filenames: false

    - id: flake8
      name: flake8
      entry: flake8 .
      language: system
      types: [python]
      pass_filenames: false

