version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run linter
          command: poetry run flake8 ./
      - run:
          name: Check formatting
          command: poetry run black --check ./ && poetry run isort --check-only ./

  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "~/family_budget_bot/scripts/deploy.sh"
          

workflows:
  sample:
    jobs:
      - build-and-test
      - deploy:
        requires:
          - build-and-test
        filters:
          branches:
            only: main

