name: Check code quality

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Install deps with poetry
        run: poetry install
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run black formatter
        run: poetry run black --check .
      - name: Run isort formatter
        run: poetry run isort --check-only .

